import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import useConnext from "../src/hooks/useConnext";

const Home: NextPage = () => {
  // this hook can be used in any nextJS/React app to consume connext SDK. Users can customize it accordingly.
  const { tracker, handleBridgeState } = useConnext();

  return (
    <div className={styles.container}>
      <Head>
        <title>Connext Next JS</title>
        <meta content="Generated by @connext/sdk" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={styles.main}>
        <div className={styles.flexDisplay}>
          <h2>Simple bridge using @connext/sdk</h2>
          <ConnectButton />
        </div>
        <div className={styles.center}>
          <button className={styles.button} onClick={() => handleBridgeState()}>
            Start Bridging
          </button>
          {tracker && (
            <p>
              You can track you xcall{" "}
              <a target="_blank" href={tracker} rel="noreferrer">
                here.
              </a>
            </p>
          )}
        </div>
      </main>
      <footer className={styles.footer}>
        *This bridge is transffering TEST tokens from goreli chain to
        goreli-optimism chain. For more information refer official connext
        documentation{" "}
        <a
          href="https://docs.connext.network/"
          target="_blank"
          rel="noreferrer"
        >
          here
        </a>
        .
      </footer>
    </div>
  );
};

export default Home;
